### ISSUE TITLE
ZenCrepes Roadmap

### ISSUE THREAD

**Issue by Fgerthoffert** [zencrepes/zencrepes#136]
Some work took place over the past few months to convert ZenCrepes from a serverless version to a more complete set of services backed by an Elasticsearch backend.

Documentation is available at https://docs.zencrepes.io/docs/
Issues can be created here: https://github.com/zencrepes/zencrepes/issues 

## Early release - v0.x
Facets with basic exploration and list views for the following datasets:
- [x] GitHub Issues
- [x] GitHub Labels
- [x] GitHub Milestones
- [x] GitHub Projects
- [x] GitHub Pullrequests
- [x] GitHub Releases
- [x] GitHub Repos
- [x] GitHub Stargazers & Watchers
- [x] GitHub Vulnerabilities
- [x] Circleci Environment Variables
- [x] Circleci Insights
- [x] Circleci Pipelines
- [x] Jira Issues

Other features:
- [x] GitHub Webhook support
- [x] Integration with Keycloak (Authentication & Authorization)
- [x] Jira to GitHub issues importer (using Github's import endpoint)

Instructions to try this early release are available here: https://docs.zencrepes.io/docs/try/

## v1.0

The next milestone is to get close to feature-parity with the serverless version of ZenCrepes currently available on https://zencrepes.io.

- [x] Github Issues, agile management & reporting
- [x] Github Labels, bulk operations
- [x] Github Issues, bulk operations 
- [x] Issues - network view (same than zencrepes.io)
- [x] Convert all codebases to Apache2 license
- [x] Update dependencies to their latest stable versions

## v1.1
[Detailed list](https://github.com/zencrepes/zencrepes/milestone/1)
- [x] New dataset to handle testing states #145 
- [x] New dataset to handle Bamboo runs #145 

## v1.2
[Detailed list](https://github.com/zencrepes/zencrepes/milestone/2)
- [ ] Issues - bulk creation from spreadsheet
- [ ] Labels - display table grouped by label name
- [ ] Watchers / Stargazers - display table grouped by user login
- [ ] Cleanup code (types mostly)
- [ ] Address stability issues with the API (mostly reduce the number of GraphQL calls) #143
